### PR TITLE
Sync feature/regional_ensda with the latest support/HAFS and master branch

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
Sync feature/regional_ensda with the latest support/HAFS, which has been synced with the latest GSI master branch.
There are changes related to the grid_type_fv3_regional development from the master branch, causing some conflicts in the src/gsi/gsi_rfv3io_mod.f90, related to the fv3_h_to_ll and fv3_h_to_ll_regular_grids subroutines. For now, the source code changes related to the grid_type_fv3_regional development are ignored in this merge, which will need to be addressed/unified in the future.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@TingLei-NOAA and @XL-OU, I am trying to using this [feature/regional_ensda_sync](https://github.com/hafs-community/GSI/tree/feature/regional_ensda_sync) branch to sync the [feature/regional_ensda](https://github.com/hafs-community/GSI/tree/feature/regional_ensda) branch with the latest [support/HAFS](https://github.com/hafs-community/GSI/tree/support/HAFS) and the authoritative master branch. There are some conflicts in the src/gsi/gsi_rfv3io_mod.f90, related to the fv3_h_to_ll and fv3_h_to_ll_regular_grids subroutines, for which I am not sure how to resolve. Appreciate it if you could help to take a look at these. If feasible, you can push your changes directly into this [feature/regional_ensda_sync](https://github.com/hafs-community/GSI/tree/feature/regional_ensda_sync) branch. Thanks!

Bin

**Comment by TingLei-NOAA** [comment]
Bin,
Sure. I will finish it as soon as possible.
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624

**Comment by TingLei-daprediction** [comment]
I have a look. Yes, the major merging problem is with the newly added grid_type_fv3_regional function ( treat two kinds of grids with different horizontally layout directions).  In fact, the current branch are using a re-consolidated subs (including fv3_h_to_ll_regular_grids)  in mod_fv3_lolgrid.f90 rather than sub like fv3_h_to_ll in mod_fv3_lola.f90.   To merge the grid_type_fv3_regional function would need some efforts.  I would suggest , right now, keep the part in this branch untouched and merge developments in the GSI master on other parts.  Please let me know the plan .

**Comment by BinLiu-NOAA** [comment]
Thanks a lot, @TingLei-NOAA! I will give it a try to see if I can build and run a few tests with this branch.

**Review by lbi2018 — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Build and low-resolution tests on Orion passed. Merging the changes into the feature/regional_ensda branch now.

**Pull request merged**
